### PR TITLE
feat: :sparkles: add save segmentation output in test script

### PR DESCRIPTION
**Pull request by PauloFavero**
This pull request will close the issue https://github.com/DonaldRR/SimpleNet/issues/19

### CODE REVIEW

**Comment by thanhthanhhp123** [comment]
Can you give me a way to contact you? I have some question. Thanks!

**Comment by PauloFavero** [comment]
> Can you give me a way to contact you? I have some question. Thanks!

You can contact me through my LinkedIn profile. You can find the link on my profile.

**Comment by DonaldRR** [comment]
Thanks for your contribution! You can contact me with donaldzhou9578@gmail.com

**Comment by Abhijeet99999** [comment]
@thanhthanhhp123 @DonaldRR , waiting for answer.

**Pull request merged**
